[pytest]
testpaths = tests
addopts =
    -v
    --html=reports/report.html
    --self-contained-html
    --metadata="Project" "OrangeHRM QA Automation"
    --metadata="Author" "Karthik Raja Nichenametla"
    --metadata="Browser" "Chrome (Headless)"
markers =
    smoke: Smoke tests - critical path only
    regression: Full regression suite
    login: Login module tests
    dashboard: Dashboard module tests
    employee: Employee module tests
    negative: Negative test cases
